# -*- coding: utf-8 -*-
"""ADT_G1A021085_ArmanVinson

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DigMcGGP9U_un4fsmSvSzOCSOrx-hjQs
"""

#menginput identitas yang akan digunakan untuk absensi
def identitas():
  input("Nama :")
  input("NPM :")
  input("Keterangan :")
  main()

#menu yang digunakan di awal
def menu():
  print('''
  Pilih Menu
  1. Mengisi Absen
  2. Selesai
''')
  pilih = (int(input("Anda memilih : ")))

  if pilih == 1:
    identitas()
  elif pilih == 2:
    print("Terima kasih sudah mengisi absensi")

print('''
==================
Absensi Sederhana
==================
Nama : Arman Vinson
NPM  : G1A021085
==================== ''')
menu()

